### ISSUE TITLE
[FR] Embed background list for Leveler

### ISSUE THREAD

**Issue by ghost** [AznStevy/Maybe-Useful-Cogs#11]
It could use Embed to show a preview in the background list otherwise it's quite hard for users to know what they want.

**Comment by AznStevy** [comment]
How would you display multiple backgrounds?

**Comment by ghost** [comment]
I'm not sure, or maybe simply have the option to see each image individually by doing something like "[p]lvlset listbgs <bgname>" or maybe we could show the whole list of pictures in pm so it doesn't spam chat?
