### ISSUE TITLE
[LEVELER] New fonts doesn't supports Cyrillic characters.

### ISSUE THREAD

**Issue by fixator10** [AznStevy/Maybe-Useful-Cogs#20]
![Screenshot: https://i.imgur.com/qapUbfF.png](https://i.imgur.com/qapUbfF.png)

**Comment by AznStevy** [comment]
Aww, ok I'll try to find a workaround. For now, you can change the font back by replacing the font_bold.tff file in the data folder with the old one.

**Comment by AznStevy** [comment]
Wait, did it work before?

**Comment by fixator10** [comment]
![Yes](https://i.imgur.com/tQuefDH.png)
Yep

**Comment by fixator10** [comment]
![Fonts compare](https://i.imgur.com/QfyEzhG.png)

**Comment by AznStevy** [comment]
Font has been changed back.
