### ISSUE TITLE
[leveler] increase exp gain

### ISSUE THREAD

**Issue by K2NK** [AznStevy/Maybe-Useful-Cogs#41]
Hi..how do i increase exp gain? so member can level up faster

**Comment by AznStevy** [comment]
Line 2661

**Comment by K2NK** [comment]
Hi..and how to reduce the server exp..
now level 16 total exp 18995 and i want to make it only 5k exp to level 16..for easy level up..
thanks

**Comment by AznStevy** [comment]
Line 2903. Please don't use this to ask questions about the cog, use the support server.

**Comment by K2NK** [comment]
Sorry bro...thanks btw

**Comment by AznStevy** [comment]
No problem. It's just that I get an email when you post one of these... so talking to me about it on discord is much more convenient.
