### ISSUE TITLE
[Leveler] Installing on a Raspberry Pi

### ISSUE THREAD

**Issue by vico93** [AznStevy/Maybe-Useful-Cogs#59]
I have a self-hosted instance of Red on my pi (raspbian stretch), but mongodb from apt isnt quite updated, and according [to this answer](https://raspberrypi.stackexchange.com/a/67919) will not due to raspbian being a ARM x86 system.

So, is still possible to run this cog on a Raspbian Red? Is there any options left?

Thanks in advance!

**Comment by AznStevy** [comment]
The current code requires mongodb. You can always try to host the server remotely on a beefier ubuntu server on DigitalOcean or something like that and then just access using the pi. Try the support server. Maybe someone there's found a hacky solution, but no promises.

**Comment by vico93** [comment]
Can you send me the link to support server?

**Comment by vico93** [comment]
Well seems like using 3.0.14 builds for pi solved me this problem.
http://andyfelong.com/2017/08/mongodb-3-0-14-for-raspbian-stretch/
