### ISSUE TITLE
[leveler]Cog doesn't load :/ 

### ISSUE THREAD

**Issue by ghost** [AznStevy/Maybe-Useful-Cogs#62]
When i try to load leveler :
[0mn = Leveler(bot)
  
File "/root/Red-DiscordBot/cogs/leveler.py", line 61, in __init__dbs = client.database_names()
  
File "lib/pymongo/mongo_client.py", line 1496, in list_database_namesfor doc in self.list_databases(session, nameOnly=True)]
  
File "lib/pymongo/mongo_client.py", line 1476, in list_databases"admin").command(cmd, session=session)
  
File "lib/pymongo/database.py", line 529, in commandwith client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  
File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
return next(self.gen)
  
File "lib/pymongo/mongo_client.py", line 982, in _socket_for_reads
server = topology.select_server(read_preference)
  
File "lib/pymongo/topology.py", line 224, in select_server
address))
  
File "lib/pymongo/topology.py", line 183, in select_servers
selector, server_timeout, address)
  
File "lib/pymongo/topology.py", line 209, in _select_servers_loop
self._description.check_compatible()
  
File "lib/pymongo/topology_description.py", line 121, in check_compatible
raise ConfigurationError(self._incompatible_err)
pymongo.errors.ConfigurationError: Server at localhost:27017 reports wire version 0, but this version of PyMongo requires at least 2 (MongoDB 2.6).

**Comment by AznStevy** [comment]
Please use the support server. I'd rather keep track of stuff there.
