### ISSUE TITLE
Leveler lags after a huge amount of users.

### ISSUE THREAD

**Issue by ncodex2** [AznStevy/Maybe-Useful-Cogs#8]
I already contacted Stevy about this, however, i figured out that it doesn't lag because it compresses a image, it lags because it makes a huge file that saves all the data, then when that hits around 2mb, the system starts to hog the CPU. I think Twentysix might be able to explain this better than me.

My recommendation: Make a save file for separate users, for example User1.json and User2.json, or make seperate discord servers json (that'll fill up quickly as well).

**Comment by nikolaaa4** [comment]
Or better yet, make save files for each user.

**Comment by AznStevy** [comment]
Yes, I'm aware. I'll fix when I get the time.

**Comment by ncodex2** [comment]
Alright, is there an ETA maybe or is it random?
